export const pageRoute = {
    empty: '',
    login: 'login',
    admin_login: 'admin-login',
    user_register: 'user-register',
    seller_register: 'seller-register',
    books: 'books',
    books_id: 'books/:id',
    cartlist: 'cart-list',
    categories: 'categories',
    collection: 'collection',
    checkout: 'checkout',
    orders: 'orders',
    wishlist: 'wishlist',
    termsofuse: 'terms-of-use',
    privacypolicy: 'privacy-policy',
    giftcards: 'gift-cards',
    rewards: 'rewards',
    myprofile: 'my-profile',
    supports: 'supports',
    advertise: 'advertise',
    veiled: '**',
}

export const collRoute = {
    empty: '',
    arts_photography: 'arts-photography',
    biographies_memoirs: 'biographies-memoirs',
    childrens_books: 'childrens-books',
    cookbook: 'cookbook',
    literature_fiction: 'literature-fiction',
    mystery_suspense: 'mystery-suspense',
    sci_fi_fantasy: 'sci-fi-fantasy',
    current_bestsellers: 'current-bestsellers',
    limited_time_offer: 'limited-time-offer',
    top_rates_book: 'top-rates-book',
}
